### PR TITLE
Changed FTP method retrieval method and default to `ensembl` annotati…

### PR DESCRIPTION
**Pull request by marcoooo**
…on.source.

Should match the updates needed in FTP dumps pipeline as well then. 

Default genebuild.annotation_source to 'ensembl'

### CODE REVIEW

**Review by bilalebi — APPROVED** [review]
This looks good to me
Based on @jonk-ebi 's requirement, we can create a separate PR later to update the return value from a list of links
```
[ 
   'link1', 
   'link2',
   ...
]
```
to a dictionary or tuple mentioning the `dataset_type` and the path associated with it, something similar to this
```
[
   {
      "dataset_type": "assembly",
      "path": "link1"
   },
   {
      "dataset_type": "genebuild",
      "path": "link2"
   }
   ...
]
```

**Comment by marcoooo** [comment]
@bilalebi do we need a release tag for this one?

**Comment by bilalebi** [comment]
> @bilalebi do we need a release tag for this one?

It will depend on whether web-team will be using these changes today or tomorrow (which I don't think it's the case)
I'm hoping to add `dataset_type` to both `api` and `grpc` reponses by Monday; Web will start implementing this feature on their end next week (~6th Feb)

**Comment by marcoooo** [comment]
ok.

> > @bilalebi do we need a release tag for this one?
> 
> It will depend on whether web-team will be using these changes today or tomorrow (which I don't think is the case?) I'm hoping to add `dataset_type` to both `api` and `grpc` responses by Monday; Web will start implementing this feature on their end next week (~6th Feb)

No need for a 2.0.0.dev3 tag then. from what you say.

**Pull request merged**
